name: test-rec-backend

on: [push]

env:
  FLASK_INPUT_FMT: lavfi
  
jobs:
  ffmpeg-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7","3.8","3.9","3.10"]

    steps:
      - uses: actions/checkout@v2
      - name: install libsndfile
        run: sudo apt-get -y update && sudo apt-get install -y libsndfile1
      - uses: FedericoCarboni/setup-ffmpeg@v1
        id: setup-ffmpeg
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
            python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          flake8 . --count --extend-ignore E231,F401 --max-line-length=127 --show-source --statistics
      - name: test ffmpeg input
        run: |
          python test.py -i
